### ISSUE TITLE
Lifecycle keywords are not recognized

### ISSUE THREAD

**Issue by drakulavich** [stefanschenk/IntelliJBehave#2]
Hi there!

First of all, thanks for you fork. It's much better than default one in Idea.
According to [story syntax](http://jbehave.org/reference/latest/story-syntax.html), there is Lifecycle block with **Before** and **After**.

Step before these two words is not recognized properly. For example:
```
Lifecycle:
Before:
Given I sign in as admin user
After:
Given I sign in as admin user
```
I've got an error: `Step 'Then Request is successful After:' is not defined`

**Comment by stefanschenk** [comment]
Thanks for reporting this issue. I will look into it.

**Comment by stefanschenk** [comment]
Fixed in version 1.61-b. Version is updated in plugin repository. Will be available start of next week.

**Comment by drakulavich** [comment]
Great news! Thanks a lot!

**Comment by stefanschenk** [comment]
@drakulavich I will close this issue now. If you find another (or the same) problem with Lifecycle keywords, please let me know.
In the next version, Lifecycle keyword completion will be added.
